### PR TITLE
Create data.yaml

### PR DESCRIPTION
**Pull request by marlonw81**
add subsection Westerwald and first city entry

### CODE REVIEW

**Comment by marians** [comment]
CI finds some errors:

```
./data/countries/de/rp/westerwald/data.yaml
  13:1      error    wrong indentation: expected 2 but found 0  (indentation)
  27:1      error    wrong indentation: expected 2 but found 0  (indentation)
```

**Comment by marians** [comment]
@marlonw81 Please also remove https://github.com/netzbegruenung/green-directory/blob/master/data/countries/de/rp/data.yaml#L309-L321 to avoid a duplicate

**Comment by marians** [comment]
@marlonw81 Will you update this PR at some point?

**Comment by marlonw81** [comment]
Hi Marian,

thank you for your info and your patience. I’m sorry for the delay. I’ll do that this week.

Best regards,
Marlon





Am 10.04.19 um 23:32 schrieb Marian Steinbach

**Comment by marians** [comment]
Closing due to inactivity.

**Pull request closed without merging**
