### PR TITLE
Schema proposal for regional party chapters

### PR DESCRIPTION
**Pull request by marians**
Work in progress

## Questions

- Do we need an attribute for the canonical name of a chapter, e. g. the Kreisverband Rheinisch-Bergischer Kreis is most often called "KV Rhein-Berg".

## TODO

- ~~Document schema proposal in README.md~~

## Help Wanted

- Please provide feedback regarding the schema, but also regarding documentation clarity.

### CODE REVIEW

**Comment by mehlukas** [comment]
I really like the idea of this project and I think using yaml files is a good idea. I would propose to use yaml schema files to validate that the correct keys/datatypes are being used.
From your example it looks like you want the file/folder structure to go down to the federal state level. So it should be 16 folders with only 1 file in them?

Regarding your question: Do you think an additional canonical name is relevant for a lot of local chapters?

**Comment by marians** [comment]
+1 for schema files and validating, ideally in CI/CD as a prerequisite for merging pull requests.

In my opinion, the directory structure shouldn't be of importance to the system really. It should make human access/maintenance as simple as possible. Ideally, we would start with a not-too-deep structure and grow deeper when needed.

Regarding the name: By now I think there may be an optional alias field. Not required to get going in a first step though.

**Comment by marians** [comment]
> Should there be a structure ("type") for the parliamentary groups as well? Going from Bundestagsfraktion over Landtagsfraktion down to Gemeinderatsfraktion?

I somebody sees a need and wants to maintain that, probably. For now I would exclude that.

**Comment by mehlukas** [comment]
ok.
So let's merge and get started 😄

**Comment by marians** [comment]
Any proposal for a YAML schema format?

**Comment by mehlukas** [comment]
```type: map
mapping:
  type: 
    type: str
  country:
    type: str
  urls:
    type: seq
    sequence:
      - type: map
        mapping:
          type:
            type: str
          url:
            type: str
  emails:
    type: seq
    sequence:
      - type: map
        mapping:
          address:
            type: str
  level:
    type: str
  state:
    type: str
  region:
    type: str
  district:
    type: str
  city:
    type: str```

this is what I would initially propose as a schema. I also wrote a small python script to check it. 
Can't I commit to your branch? Sorry - github newbie 😄

**Comment by marians** [comment]
You can fork the repo, then provide a pull request to be merged into the `schema-proposal` of this repo. Your commits would then land here in PR #1.

Is that schema definition home-grown? If possible, I'd like to work with some def-facto standard. If there is no such thing, then I'd like use JSON-schema. The validation would simply rely on prior conversion between YAML and JSON.

**Comment by mehlukas** [comment]
The schema is in yaml format itself, and I defined it to match the data structure according to [Pykwalify](http://pykwalify.readthedocs.io/en/master/basics.html), the library I used to check the schema.
But if you want, we can also use a json schema definition, but I think the yaml schema definition is a defacto standard as well.

**Comment by mehlukas** [comment]
See my proposal for schema validation in [#2](https://github.com/netzbegruenung/green-directory/pull/2)

**Comment by marians** [comment]
@mehlukas I merged your contribution. Thanks! Validation is now automatically executed in TravisCI. Click one of the green hooks on the commits or go to the last one: https://travis-ci.org/netzbegruenung/green-directory/builds/356518709

As a standard policy for this repo, I'd like reviews before pull requests are merged. This is enforced in the repo settings. So I'd welcome your review.

**Comment by mehlukas** [comment]
I don't have any experience with Travis, but shouldn't we change `c.validate(raise_exception=False)` to `True` for the check to work? Otherwise pykwalify will only write to stdout and the script will always exit with status 0.

**Comment by marians** [comment]
Changed.

Also change the `validate.py` script to be executed from the repository's root.

**Comment by marians** [comment]
Thanks for the review! Let your data contributions come!

**Pull request merged**
